server:
  post: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: currency-exchange_route
        uri: lb://currency-exchange-service
        predicates:
          - Path=/v1/api/currency-exchange/**
        filters:
          - CustomFilter
      - id: currency-conversion_route
        uri: lb://currency-conversion-service
        predicates:
          - Path=/v1/api/currency-conversion/**
        filters:
          - CustomFilter
